version: 2

models:
    - name: stg_orders
      description: "All orders details"
      columns:
          - name: order_id
            description: "The primary key for this table"
           

    - name: fct_orders
      description: "All details including customers"
      columns:
          - name: id
            description: "The primary key for this table"
            
